### PR TITLE
initial fuzzing functionality

### PR DESCRIPTION
**Pull request by bxatnarf**
Implemented as web service.  Requires `filename` argument in same format as `clean_test_files`, which is the base file on which mutations are performed.  Fuzzer results are named after the original file w/ an added string to make the name unique and are stored in `files/fuzzed` .  

Fuzzing happens in a separate thread pool to prevent the web request from timing out.  You can query the `pending_fuzz` endpoint  (w/ a filename argument) to see how many fuzzing instances are pending.

Currently uses `pyjfuzz` as a mutator.  Can support additional mutators in the future.

### CODE REVIEW

**Comment by prashantbarca** [comment]
I think we should make it mutually exclusive to use either --fuzz, --generate, or --file. It might not make sense to have both --fuzz and --generate together. Perhaps we should also rename --generate to --synthea?

**Comment by bxatnarf** [comment]
It needs a file as an input for fuzzing, so allowing  `--fuzz --generate` is mostly for testing convenience so you do not need to specify `--file` every time.  Although `--file` has more narrow requirements when used with `--fuzz` (it **must** be a file in `files/fhir` ), so  it makes sense to make `--fuzz` mutually exclusive with `--file`.     

Perhaps we should fully separate fuzzing from telephone -- I can move the fuzzing bits  to its own python file in `tools/fuzz.py`, and all it will do is generate fuzzed files.

**Comment by prashantbarca** [comment]
Perhaps we should support a syntax where we request multiple files from the fuzzing 

`@app.route("/fuzz/<filename>/<count>")`

**Comment by bxatnarf** [comment]
Currently `count` is accepted as an optional URL parameter, e.g., `/fuzz/<filename>/?count=1` .  I can move it to be a url parameter if you prefer that syntax

> Perhaps we should support a syntax where we request multiple files from the fuzzing
> 
> `@app.route("/fuzz/<filename>/<count>")`

**Comment by prashantbarca** [comment]
That works fine, actually. Are you making any other changes here, or should I merge this branch?

**Review by prashantbarca — APPROVED** [review]

**Pull request merged**
